### ISSUE TITLE
Package is installing typing, even for python version  > 3.5

### ISSUE THREAD

**Issue by Hartorn** [avidml/avidtools#6]
Hello :)

We are using your package, and encounter a small issue : 
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bazire/giskard/.venv/lib/python3.10/site-packages/debugpy/adapter/__main__.py", line 215, in <module>
    __import__("debugpy")
  File "/home/bazire/giskard/.venv/lib/python3.10/site-packages/debugpy/adapter/../../debugpy/__init__.py", line 35, in <module>
    from debugpy.public_api import *  # noqa
  File "/home/bazire/giskard/.venv/lib/python3.10/site-packages/debugpy/adapter/../../debugpy/public_api.py", line 8, in <module>
    import typing
  File "/home/bazire/giskard/.venv/lib/python3.10/site-packages/debugpy/adapter/../../typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/home/bazire/giskard/.venv/lib/python3.10/site-packages/debugpy/adapter/../../typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
^CTraceback (most recent call last):
```
It's making debugpy fail, when trying to debug code.

It's actually only a small fix to do : could you change requirement from `typing` to `typing;python_version<"3.5"` as descirbed [here](https://pypi.org/project/typing/)

Thanks ! :)

**Comment by Hartorn** [comment]
I did a pr to fix this, see https://github.com/avidml/avidtools/pull/7

Would be great to have a new version with this fix :)

**Comment by shubhobm** [comment]
Fixed in https://github.com/avidml/avidtools/pull/7
